-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 17:18:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exo_chaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exo_chaussure` ;

-- -----------------------------------------------------
-- Schema exo_chaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exo_chaussure` DEFAULT CHARACTER SET utf8 ;
USE `exo_chaussure` ;

-- -----------------------------------------------------
-- Table `exo_chaussure`.`TypeUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`TypeUtilisateur` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`TypeUtilisateur` (
  `idTypeUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUtilisateur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`RegioDept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`RegioDept` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`RegioDept` (
  `idRegioDept` INT NOT NULL AUTO_INCREMENT,
  `numDept` VARCHAR(3) NOT NULL,
  `nomDept` VARCHAR(45) NOT NULL,
  `nomRegion` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idRegioDept`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Ville` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `cp` INT(5) NOT NULL,
  `nomVille` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idVille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomutilisateur` VARCHAR(255) NOT NULL,
  `prenomUtilisateur` VARCHAR(100) NOT NULL,
  `numRueUtilisateur` VARCHAR(6) NULL,
  `nomRueUtilisateur` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `pays` VARCHAR(45) NOT NULL,
  `statutUtilisateur` TINYINT(1) NULL,
  `TypeUtilisateur_idTypeUtilisateur` INT NOT NULL,
  `RegioDept_idRegioDept` INT NOT NULL,
  `Ville_idVille` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  INDEX `fk_Utilisateur_TypeUtilisateur1_idx` (`TypeUtilisateur_idTypeUtilisateur` ASC),
  INDEX `fk_Utilisateur_RegioDept1_idx` (`RegioDept_idRegioDept` ASC),
  INDEX `fk_Utilisateur_Ville1_idx` (`Ville_idVille` ASC),
  CONSTRAINT `fk_Utilisateur_TypeUtilisateur1`
    FOREIGN KEY (`TypeUtilisateur_idTypeUtilisateur`)
    REFERENCES `exo_chaussure`.`TypeUtilisateur` (`idTypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_RegioDept1`
    FOREIGN KEY (`RegioDept_idRegioDept`)
    REFERENCES `exo_chaussure`.`RegioDept` (`idRegioDept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Ville1`
    FOREIGN KEY (`Ville_idVille`)
    REFERENCES `exo_chaussure`.`Ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Taille` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Taille` (
  `idTaille` INT NOT NULL AUTO_INCREMENT,
  `nomTaille` INT(2) NOT NULL,
  `statutTaille` TINYINT(1) NULL,
  `Taillecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTaille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `nomCategorie` VARCHAR(45) NOT NULL,
  `statutCategorie` TINYINT(1) NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Genre` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `nomGenre` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Couleur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Couleur` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Couleur` (
  `idCouleur` INT NOT NULL AUTO_INCREMENT,
  `nomCouleur` VARCHAR(45) NOT NULL,
  `statutCouleur` TINYINT(1) NULL,
  PRIMARY KEY (`idCouleur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Tva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Tva` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Tva` (
  `idTva` INT NOT NULL AUTO_INCREMENT,
  `Tvacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Produit` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(100) NOT NULL,
  `descProduit` VARCHAR(255) NOT NULL,
  `prixHTProduit` DECIMAL(6,2) NOT NULL,
  `refProduit` VARCHAR(45) NOT NULL,
  `vipProduit` TINYINT(1) NOT NULL,
  `noteProduit` DECIMAL(3,1) NULL,
  `statutProduit` TINYINT(1) NULL,
  `Taille_idTaille` INT NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  `Couleur_idCouleur` INT NOT NULL,
  `Tva_idTva` INT NOT NULL,
  PRIMARY KEY (`idProduit`),
  UNIQUE INDEX `nomProduit_UNIQUE` (`nomProduit` ASC),
  INDEX `fk_Produit_Taille1_idx` (`Taille_idTaille` ASC),
  INDEX `fk_Produit_Categorie1_idx` (`Categorie_idCategorie` ASC),
  INDEX `fk_Produit_Genre1_idx` (`Genre_idGenre` ASC),
  INDEX `fk_Produit_Couleur1_idx` (`Couleur_idCouleur` ASC),
  INDEX `fk_Produit_Tva1_idx` (`Tva_idTva` ASC),
  CONSTRAINT `fk_Produit_Taille1`
    FOREIGN KEY (`Taille_idTaille`)
    REFERENCES `exo_chaussure`.`Taille` (`idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `exo_chaussure`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `exo_chaussure`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Couleur1`
    FOREIGN KEY (`Couleur_idCouleur`)
    REFERENCES `exo_chaussure`.`Couleur` (`idCouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Tva1`
    FOREIGN KEY (`Tva_idTva`)
    REFERENCES `exo_chaussure`.`Tva` (`idTva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Commande` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NOT NULL,
  `qteCommande` VARCHAR(45) NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Produit_idProduit` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Commande_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Commande_Produit1_idx` (`Produit_idProduit` ASC),
  CONSTRAINT `fk_Commande_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `exo_chaussure`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `exo_chaussure`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Banque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Banque` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Banque` (
  `idBanque` INT NOT NULL AUTO_INCREMENT,
  `nomBanque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBanque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Banque_Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Banque_Utilisateur` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Banque_Utilisateur` (
  `Banque_idBanque` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`Banque_idBanque`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Banque_has_Utilisateur_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Banque_has_Utilisateur_Banque_idx` (`Banque_idBanque` ASC),
  CONSTRAINT `fk_Banque_has_Utilisateur_Banque`
    FOREIGN KEY (`Banque_idBanque`)
    REFERENCES `exo_chaussure`.`Banque` (`idBanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banque_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `exo_chaussure`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Entrepot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Entrepot` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Entrepot` (
  `idEntrepot` INT NOT NULL AUTO_INCREMENT,
  `nomEntrepot` VARCHAR(100) NOT NULL,
  `qte` INT NULL,
  `statutEntrepot` TINYINT(1) NULL,
  `Commande_idCommande` INT NOT NULL,
  `Produit_idProduit` INT NOT NULL,
  PRIMARY KEY (`idEntrepot`),
  INDEX `fk_Entrepot_Commande1_idx` (`Commande_idCommande` ASC),
  INDEX `fk_Entrepot_Produit1_idx` (`Produit_idProduit` ASC),
  CONSTRAINT `fk_Entrepot_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `exo_chaussure`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrepot_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `exo_chaussure`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Materiel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Materiel` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Materiel` (
  `idMateriel` INT NOT NULL AUTO_INCREMENT,
  `nomMateriel` VARCHAR(45) NOT NULL,
  `statutMateriel` TINYINT(1) NULL,
  PRIMARY KEY (`idMateriel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo_chaussure`.`Produit_Materiel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo_chaussure`.`Produit_Materiel` ;

CREATE TABLE IF NOT EXISTS `exo_chaussure`.`Produit_Materiel` (
  `Produit_idProduit` INT NOT NULL,
  `Materiel_idMateriel` INT NOT NULL,
  PRIMARY KEY (`Produit_idProduit`, `Materiel_idMateriel`),
  INDEX `fk_Produit_has_Materiel_Materiel1_idx` (`Materiel_idMateriel` ASC),
  INDEX `fk_Produit_has_Materiel_Produit1_idx` (`Produit_idProduit` ASC),
  CONSTRAINT `fk_Produit_has_Materiel_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `exo_chaussure`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Materiel_Materiel1`
    FOREIGN KEY (`Materiel_idMateriel`)
    REFERENCES `exo_chaussure`.`Materiel` (`idMateriel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
