-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 12:15:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestionProduit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestionProduit` ;

-- -----------------------------------------------------
-- Schema gestionProduit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestionProduit` ;
USE `gestionProduit` ;

-- -----------------------------------------------------
-- Table `gestionProduit`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionProduit`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `gestionProduit`.`Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `nomCategorie` VARCHAR(45) NOT NULL,
  `descripCategorie` VARCHAR(100) NOT NULL,
  `statutCategorie` VARCHAR(45) NOT NULL,
  `dateAjoutCategorie` DATE NOT NULL,
  `dateModifCategorie` DATE NULL,
  `raisonModifCategorie` VARCHAR(45) NULL,
  `Product_idProduct` INT NOT NULL,
  `Product_Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idCategorie`, `Product_idProduct`, `Product_Categorie_idCategorie`),
  INDEX `fk_Categorie_Product1_idx` (`Product_idProduct` ASC, `Product_Categorie_idCategorie` ASC),
  CONSTRAINT `fk_Categorie_Product1`
    FOREIGN KEY (`Product_idProduct` , `Product_Categorie_idCategorie`)
    REFERENCES `gestionProduit`.`Product` (`idProduct` , `Categorie_idCategorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestionProduit`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestionProduit`.`Product` ;

CREATE TABLE IF NOT EXISTS `gestionProduit`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(100) NOT NULL,
  `descripProduit` VARCHAR(45) NOT NULL,
  `prixProduit` DECIMAL(6,2) NOT NULL,
  `statutProduit` VARCHAR(45) NOT NULL,
  `dateAjoutProduit` DATE NOT NULL,
  `dateModifProduit` DATE NULL,
  `raisonModifProduit` VARCHAR(100) NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `Categorie_idCategorie`),
  INDEX `fk_Product_Categorie_idx` (`Categorie_idCategorie` ASC),
  CONSTRAINT `fk_Product_Categorie`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `gestionProduit`.`Categorie` (`idCategorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
