vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /libs/images/products
            upload_destination: '%kernel.project_dir%/public/libs/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer