-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 09:07:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema immobilier
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `immobilier` ;

-- -----------------------------------------------------
-- Schema immobilier
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immobilier` DEFAULT CHARACTER SET utf8 ;
USE `immobilier` ;

-- -----------------------------------------------------
-- Table `immobilier`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immobilier`.`contact` ;

CREATE TABLE IF NOT EXISTS `immobilier`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NOT NULL,
  `adresse1` VARCHAR(100) NOT NULL,
  `adresse2` VARCHAR(100) NULL,
  `pays` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontact` ASC),
  PRIMARY KEY (`idcontact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immobilier`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immobilier`.`detail` ;

CREATE TABLE IF NOT EXISTS `immobilier`.`detail` (
  `iddetail` INT NOT NULL AUTO_INCREMENT,
  `descdetail` TEXT(10000) NOT NULL,
  PRIMARY KEY (`iddetail`),
  UNIQUE INDEX `iddetail_UNIQUE` (`iddetail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immobilier`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immobilier`.`location` ;

CREATE TABLE IF NOT EXISTS `immobilier`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `titreLocation` VARCHAR(100) NOT NULL,
  `resumeLocation` VARCHAR(100) NOT NULL,
  `imageLocation` VARCHAR(255) NOT NULL,
  `detail_iddetail` INT NOT NULL,
  PRIMARY KEY (`idlocation`),
  INDEX `fk_location_detail_idx` (`detail_iddetail` ASC),
  CONSTRAINT `fk_location_detail`
    FOREIGN KEY (`detail_iddetail`)
    REFERENCES `immobilier`.`detail` (`iddetail`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
