-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 11:50:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetimmo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetimmo` ;

-- -----------------------------------------------------
-- Schema projetimmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetimmo` DEFAULT CHARACTER SET utf8 ;
USE `projetimmo` ;

-- -----------------------------------------------------
-- Table `projetimmo`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`adresse` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`adresse` (
  `idadresse` INT NOT NULL AUTO_INCREMENT,
  `adresse1` VARCHAR(100) NOT NULL,
  `adresse2` VARCHAR(100) NULL,
  `ville` VARCHAR(255) NOT NULL,
  `codepostal` INT(5) NOT NULL,
  `pays` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idadresse`),
  UNIQUE INDEX `idadresse_UNIQUE` (`idadresse` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`bien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`bien` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`bien` (
  `idbien` INT NOT NULL AUTO_INCREMENT,
  `titreBien` VARCHAR(100) NOT NULL,
  `typeAnnonce` VARCHAR(45) NOT NULL,
  `typeBien` VARCHAR(100) NOT NULL,
  `resumeBien` VARCHAR(255) NOT NULL,
  `superficieBien` INT NOT NULL,
  `nbpieceBien` INT NULL,
  `prixBien` INT NOT NULL,
  `descBien` TEXT(10000) NULL,
  `imageBien` VARCHAR(255) NOT NULL,
  `statusBien` TINYINT(1) NULL,
  `datecreaBien` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datemodifBien` DATETIME NULL,
  `adresse_idadresse` INT NOT NULL,
  PRIMARY KEY (`idbien`),
  INDEX `fk_bien_adresse1_idx` (`adresse_idadresse` ASC),
  CONSTRAINT `fk_bien_adresse1`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `projetimmo`.`adresse` (`idadresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`contact` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `emailContact` VARCHAR(100) NOT NULL,
  `typeAnnonceContact` VARCHAR(45) NOT NULL,
  `typeBienContact` VARCHAR(100) NOT NULL,
  `villechercheeContact` VARCHAR(100) NOT NULL,
  `messageContact` TEXT(10000) NOT NULL,
  `bien_idbien` INT NOT NULL,
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontact` ASC),
  PRIMARY KEY (`idcontact`),
  INDEX `fk_contact_bien1_idx` (`bien_idbien` ASC),
  CONSTRAINT `fk_contact_bien1`
    FOREIGN KEY (`bien_idbien`)
    REFERENCES `projetimmo`.`bien` (`idbien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`users` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `mailUser` VARCHAR(200) NOT NULL,
  `mdpUser` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`agence` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`agence` (
  `idagence` INT NOT NULL AUTO_INCREMENT,
  `nomAgence` VARCHAR(100) NOT NULL,
  `nomRepreAgence` VARCHAR(100) NOT NULL,
  `prenomRepreAgence` VARCHAR(100) NOT NULL,
  `adresse_idadresse` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idagence`),
  UNIQUE INDEX `idagence_UNIQUE` (`idagence` ASC),
  INDEX `fk_agence_adresse1_idx` (`adresse_idadresse` ASC),
  INDEX `fk_agence_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_agence_adresse1`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `projetimmo`.`adresse` (`idadresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agence_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `projetimmo`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`client` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(100) NOT NULL,
  `prenomClient` VARCHAR(100) NOT NULL,
  `adresse_idadresse` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC),
  INDEX `fk_client_adresse1_idx` (`adresse_idadresse` ASC),
  INDEX `fk_client_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_client_adresse1`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `projetimmo`.`adresse` (`idadresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `projetimmo`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`agence_has_bien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`agence_has_bien` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`agence_has_bien` (
  `agence_idagence` INT NOT NULL,
  `bien_idbien` INT NOT NULL,
  PRIMARY KEY (`agence_idagence`, `bien_idbien`),
  INDEX `fk_agence_has_bien_bien1_idx` (`bien_idbien` ASC),
  INDEX `fk_agence_has_bien_agence1_idx` (`agence_idagence` ASC),
  CONSTRAINT `fk_agence_has_bien_agence1`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `projetimmo`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agence_has_bien_bien1`
    FOREIGN KEY (`bien_idbien`)
    REFERENCES `projetimmo`.`bien` (`idbien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
